os: centos7
sku: ocata
version: latest
contrailregistry: opencontrailnightly
orchestrator: openstack
admin_password: c0ntrail123
mysql_password: c0ntrail123
contrail_rabbitmq_port: 5673

kolla_registry: docker.io
kolla_namespace: kolla
kolla_internal_vip_address: "{{ auth_ip }}"
vrouter_id: "{{ 255 | random }}"
kolla_external_vip_interface: "eth0"
network_interface: "eth0"
rabbitmq_user: openstack
metadata_secret: c0ntrail123
keystone_version: v3
