- hosts: localhost
  gather_facts: no
  tasks:
    - add_host:
        name: "{{ item.value.ip }}"
        ansible_ssh_host: "{{ item.value.ip }}"
        ansible_ssh_user: "{{ item.value.ansible_user | default('root') }}"
        ansible_ssh_pass: "{{ item.value.ansible_ssh_pass | default('c0ntrail123') }}"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        group: "container_hosts"
      with_dict: "{{ instances }}"

- hosts: container_hosts
  gather_facts: no
  become: true
  become_user: root
  roles:
  - install_packages
  environment:
    ANSIBLE_HOST_KEY_CHECKING: 'false'
    ANSIBLE_STDOUT_CALLBACK: debug
  pre_tasks:
    - name: install python
      command: 'apt-get install python-minimal'
