---

- name: check added hosts
  debug:
    msg: "Added hosts"

- name: copy deployment to temp variable
  set_fact:
     tmp_deployment: "{{ deployment }}"
  when: deployment is defined

- name: set default deployment
  vars:
    types:
      kolla:
      contrail:
  set_fact:
    deployment: "{{ deployment|default({})|combine({'type': types }) }}"
  when: deployment is undefined or deployment.type is undefined

- name: install packages for contrail helm deployer
  include: contrail-helm/main.yml
  when: deployment.type.helm is defined

- name: install packages for openshift ansible deployer
  include: openshift-ansible/main.yml
  when: deployment.type.openshift is defined

- name: set insecure registry
  include: insecure_registry.yaml
  when: deployment.type.kolla is defined

